name: ECU Simulation & Visualization

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  simulate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install matplotlib

    - name: Run ECU Simulation
      run: |
        python main.py

    - name: Generate Visualization
      run: |
        python tools/visualize_log.py

    - name: Upload Chart as Artifact
      uses: actions/upload-artifact@v3
      with:
        name: ecu-graph
        path: ecu_graph.png
